title: "Eros Sistemes Operatius"
author: "Eros"
description: "Curs de Sistemes Operatius — recursos, pràctiques i documentació."
baseurl: ""
url: "https://erosmauri.github.io"

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
