site_name: Eros Sistemes Operatius
site_author: Eros

theme:
  name: material
  custom_dir: assetscss
  favicon: favicon-32x32.png
  logo: favicon-32x32.png
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep-orange
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Fira Sans
    code: Fira Code

  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assetscss/extra.css
  - assetscss/password-protect.css

nav:
  - Home: index.md

copyright: |
  &copy; 2025 <a href="https://github.com/erosmauri" target="_blank" rel="noopener">Eros</a>
